import { CanonicalFieldDefinition, PlatformSource } from "../types";

export const CANONICAL_FIELDS: CanonicalFieldDefinition[] = [
  // Dimensions
  { id: "date", label: "Date", category: "dimension", dataType: "date", required: true },
  { id: "platform", label: "Platform", category: "dimension", dataType: "string" },
  { id: "dataSource", label: "Data Source", category: "dimension", dataType: "string" },
  { id: "account", label: "Account", category: "dimension", dataType: "string" },
  { id: "appName", label: "App Name", category: "dimension", dataType: "string" },
  { id: "appId", label: "App ID", category: "dimension", dataType: "string" },
  { id: "os", label: "Operating System", category: "dimension", dataType: "string" },
  { id: "appVersion", label: "App Version", category: "dimension", dataType: "string" },
  { id: "campaign", label: "Campaign", category: "dimension", dataType: "string" },
  { id: "campaignId", label: "Campaign ID", category: "dimension", dataType: "string" },
  { id: "campaignStatus", label: "Campaign Status", category: "dimension", dataType: "string" },
  { id: "adSet", label: "Ad Set", category: "dimension", dataType: "string" },
  { id: "adSetId", label: "Ad Set ID", category: "dimension", dataType: "string" },
  { id: "ad", label: "Ad", category: "dimension", dataType: "string" },
  { id: "adId", label: "Ad ID", category: "dimension", dataType: "string" },
  { id: "country", label: "Country", category: "dimension", dataType: "string" },
  { id: "region", label: "Region", category: "dimension", dataType: "string" },
  { id: "network", label: "Network", category: "dimension", dataType: "string" },
  { id: "adFormat", label: "Ad Format", category: "dimension", dataType: "string" },
  { id: "placement", label: "Placement", category: "dimension", dataType: "string" },
  { id: "device", label: "Device", category: "dimension", dataType: "string" },
  { id: "currency", label: "Currency", category: "dimension", dataType: "string" },
  { id: "attributionWindow", label: "Attribution Window", category: "dimension", dataType: "string" },

  // Acquisition
  { id: "spend", label: "Spend", category: "acquisition", dataType: "currency" },
  { id: "impressions", label: "Impressions", category: "acquisition", dataType: "number" },
  { id: "clicks", label: "Clicks", category: "acquisition", dataType: "number" },
  { id: "installs", label: "Installs", category: "acquisition", dataType: "number" },
  { id: "conversions", label: "Conversions", category: "acquisition", dataType: "number" },
  { id: "viewThroughConversions", label: "View-Through Conversions", category: "acquisition", dataType: "number" },
  { id: "inAppActions", label: "In-App Actions", category: "acquisition", dataType: "number" },

  // Monetization
  { id: "adRevenue", label: "Ad Revenue", category: "monetization", dataType: "currency" },
  { id: "iapRevenue", label: "IAP Revenue", category: "monetization", dataType: "currency" },
  { id: "subscriptionRevenue", label: "Subscription Revenue", category: "monetization", dataType: "currency" },
  { id: "platformConversionValue", label: "Platform Conversion Value", category: "monetization", dataType: "currency" },
  { id: "adImpressions", label: "Ad Impressions", category: "monetization", dataType: "number" },
  { id: "matchedRequests", label: "Matched Requests", category: "monetization", dataType: "number" },
  { id: "adRequests", label: "Ad Requests", category: "monetization", dataType: "number" },

  // Engagement
  { id: "users", label: "Users", category: "engagement", dataType: "number" },
  { id: "newUsers", label: "New Users", category: "engagement", dataType: "number" },
  { id: "activeUsers", label: "Active Users", category: "engagement", dataType: "number" },
  { id: "dau", label: "DAU", category: "engagement", dataType: "number" },
  { id: "wau", label: "WAU", category: "engagement", dataType: "number" },
  { id: "mau", label: "MAU", category: "engagement", dataType: "number" },
  { id: "sessions", label: "Sessions", category: "engagement", dataType: "number" },
  { id: "sessionDuration", label: "Session Duration", category: "engagement", dataType: "number" },
  { id: "retainedUsersD1", label: "D1 Retained Users", category: "engagement", dataType: "number" },
  { id: "eligibleNewUsersD1", label: "D1 Eligible New Users", category: "engagement", dataType: "number" },
  { id: "retainedUsersD7", label: "D7 Retained Users", category: "engagement", dataType: "number" },
  { id: "eligibleNewUsersD7", label: "D7 Eligible New Users", category: "engagement", dataType: "number" },
  { id: "retainedUsersD30", label: "D30 Retained Users", category: "engagement", dataType: "number" },
  { id: "eligibleNewUsersD30", label: "D30 Eligible New Users", category: "engagement", dataType: "number" },
  { id: "crashes", label: "Crashes", category: "engagement", dataType: "number" },
  { id: "crashFreeUsers", label: "Crash-Free Users", category: "engagement", dataType: "number" },
];

export const REQUIRED_FIELD_IDS = ["date"];

export function fieldById(id: string): CanonicalFieldDefinition | undefined {
  return CANONICAL_FIELDS.find((f) => f.id === id);
}

// Normalize a raw header for comparison: lowercase, strip punctuation/whitespace.
export function normalizeHeader(header: string): string {
  return header
    .toLowerCase()
    .replace(/[_\-/().%]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

// Synonym dictionary: canonical field id -> known header variants (normalized).
export const FIELD_SYNONYMS: Record<string, string[]> = {
  date: ["date", "day", "report date", "event date"],
  platform: ["platform", "source", "media source"],
  dataSource: ["data source", "source"],
  account: ["account", "account name", "account id"],
  appName: ["app", "app name", "application", "game"],
  appId: ["app id", "bundle id", "package name", "app store id"],
  os: ["os", "platform os", "operating system"],
  appVersion: ["app version", "version", "version name", "build version"],
  campaign: ["campaign", "campaign name"],
  campaignId: ["campaign id"],
  campaignStatus: ["campaign status", "status"],
  adSet: ["ad set", "adset", "ad set name", "ad group", "ad group name"],
  adSetId: ["ad set id", "adset id", "ad group id"],
  ad: ["ad", "ad name", "creative", "creative name"],
  adId: ["ad id", "creative id"],
  country: ["country", "country code", "geo"],
  region: ["region", "state", "sub region"],
  network: ["network", "ad network", "partner"],
  adFormat: ["ad format", "format", "creative type"],
  placement: ["placement", "placement name"],
  device: ["device", "device type", "device category"],
  currency: ["currency", "currency code"],
  attributionWindow: ["attribution window", "attribution", "click window"],

  spend: ["cost", "spend", "amount spent", "amount spent usd", "ad spend"],
  impressions: ["impressions", "impr"],
  clicks: ["clicks", "link clicks"],
  installs: ["installs", "install", "app installs"],
  conversions: ["conversions", "conversion"],
  viewThroughConversions: ["view through conversions", "view through conv", "vtc"],
  inAppActions: ["in app actions", "in app action", "in app events"],

  adRevenue: ["ad revenue", "estimated earnings", "earnings", "revenue ads"],
  iapRevenue: ["iap revenue", "in app purchase revenue", "purchase revenue", "iap"],
  subscriptionRevenue: ["subscription revenue", "subscriptions revenue"],
  platformConversionValue: ["conversion value", "conv value", "total conversion value"],
  adImpressions: ["ad impressions", "matched requests impressions"],
  matchedRequests: ["matched requests"],
  adRequests: ["ad requests"],

  users: ["users", "total users"],
  newUsers: ["new users"],
  activeUsers: ["active users"],
  dau: ["dau", "daily active users"],
  wau: ["wau", "weekly active users"],
  mau: ["mau", "monthly active users"],
  sessions: ["sessions"],
  sessionDuration: ["session duration", "avg session duration", "average session length"],
  retainedUsersD1: ["d1 retained users", "day 1 retained users"],
  eligibleNewUsersD1: ["d1 eligible users", "day 1 cohort size"],
  retainedUsersD7: ["d7 retained users", "day 7 retained users"],
  eligibleNewUsersD7: ["d7 eligible users", "day 7 cohort size"],
  retainedUsersD30: ["d30 retained users", "day 30 retained users"],
  eligibleNewUsersD30: ["d30 eligible users", "day 30 cohort size"],
  crashes: ["crashes", "crash count"],
  crashFreeUsers: ["crash free users"],
};

// Per-platform templates: exact header (as commonly exported) -> canonical field id.
// Used both for platform auto-detection (score = overlap) and for high-confidence suggested mapping.
export const PLATFORM_TEMPLATES: Record<PlatformSource, Record<string, string>> = {
  google_ads: {
    "campaign status": "campaignStatus",
    campaign: "campaign",
    budget: "__ignore",
    "budget type": "__ignore",
    "currency code": "currency",
    status: "campaignStatus",
    "optimization score": "__ignore",
    "campaign type": "adFormat",
    "cost / install": "__ignore",
    "cost / in app action": "__ignore",
    "view through conversions": "viewThroughConversions",
    installs: "installs",
    "in app actions": "inAppActions",
    cost: "spend",
    "conversion rate": "__ignore",
    "conversion value": "platformConversionValue",
    "conversion value / cost": "__ignore",
    conversions: "conversions",
    "cost / conversion": "__ignore",
    "original conversion value": "__ignore",
  },
  admob: {
    date: "date",
    app: "appName",
    "ad unit": "placement",
    format: "adFormat",
    country: "country",
    requests: "adRequests",
    "matched requests": "matchedRequests",
    "match rate": "__ignore",
    impressions: "adImpressions",
    "fill rate": "__ignore",
    clicks: "clicks",
    ctr: "__ignore",
    "estimated earnings": "adRevenue",
    "observed ecpm": "__ignore",
  },
  axon: {
    date: "date",
    platform: "os",
    network: "network",
    campaign: "campaign",
    country: "country",
    spend: "spend",
    impressions: "impressions",
    clicks: "clicks",
    installs: "installs",
    revenue: "iapRevenue",
  },
  applovin: {
    day: "date",
    application: "appName",
    platform: "os",
    "ad network": "network",
    "ad format": "adFormat",
    country: "country",
    impressions: "adImpressions",
    "estimated revenue": "adRevenue",
    ecpm: "__ignore",
  },
  game_analytics: {
    date: "date",
    "app version": "appVersion",
    platform: "os",
    country: "country",
    "new users": "newUsers",
    dau: "dau",
    wau: "wau",
    mau: "mau",
    sessions: "sessions",
    "avg session length": "sessionDuration",
    "d1 retention": "__ignore",
    "d7 retention": "__ignore",
    "iap revenue": "iapRevenue",
  },
  firebase: {
    date: "date",
    "app version": "appVersion",
    platform: "os",
    country: "country",
    "new users": "newUsers",
    "active users": "activeUsers",
    "total users": "users",
    "in app purchase revenue": "iapRevenue",
    "crash free users": "crashFreeUsers",
    crashes: "crashes",
  },
  meta_ads: {
    day: "date",
    "campaign name": "campaign",
    "ad set name": "adSet",
    "ad name": "ad",
    "delivery status": "campaignStatus",
    country: "country",
    "amount spent usd": "spend",
    impressions: "impressions",
    "link clicks": "clicks",
    installs: "installs",
    "app installs": "installs",
    purchases: "conversions",
    "purchases conversion value": "platformConversionValue",
  },
  generic: {},
};
